unstoppabledomains/dev-docs

login-with-unstoppable/get-started-login/integration-pathways.md
login-with-unstoppable/login-integration-guides/login-without-popup.md

Reworking login integration paths selection to make features of, and distinctions between, integration options as simple as possible to identify at a glance.

Login integration paths redesign

---

login-with-unstoppable/get-started-login.md
login-with-unstoppable/libraries/uauth-bnc-onboard.md
login-with-unstoppable/libraries/uauth-overview.md
login-with-unstoppable/libraries/uauth-web3-onboard.md
login-with-unstoppable/libraries/web3-onboard-uauth.md
login-with-unstoppable/login-integration-guides/auth0-guide.md
login-with-unstoppable/login-integration-guides/bnc-onboard-guide.md
login-with-unstoppable/login-integration-guides/moralis-guide.md
login-with-unstoppable/login-integration-guides/uauth-web3-onboard-guide.md
login-with-unstoppable/login-integration-guides/web3-modal-guide.md
login-with-unstoppable/login-integration-guides/web3-onboard-guide.md
login-with-unstoppable/login-integration-guides/web3-react-guide.md
login-with-unstoppable/login-integration-guides/web3-react-v6-guide.md
login-with-unstoppable/sidebars.yaml

Updating guides and references for the new `@web3-onboard/uauth` module.

[TW-525] New Blocknative Web3-Onboard guide

---

login-with-unstoppable/index.md

modified to include Solana

---

developer-toolkit/index.md

added a summary 1-liner

---

login-with-unstoppable/index.md

added tutorial video to home page

---

login-with-unstoppable/login-integration-guides/login-with-popup.md
login-with-unstoppable/login-integration-guides/web3-react-guide.md
login-with-unstoppable/troubleshoot/troubleshooting-guide.md

Demo Video Additions 

---

login-with-unstoppable/login-integration-guides/web3-onboard-guide.md

Added demo video for LWU Blocknative Web3-Onboard integration

added tutorial demo video

---

login-with-unstoppable/login-integration-guides/web3-onboard-guide.md

fixing figure

---

openapi/loginref.page.yaml
openapi/reference.page.yaml
openapi/resolution.page.yaml

https://linear.app/unstoppable-domains/issue/REG-814/move-api-v2-openapi-spec-into-main-repo

[REG-814] - Add curl samples

---

index.mdx

Update Landing Page to use Browse By Product.

Updated to view Browse By Product section

---

index.mdx
smart-contracts/contract-reference/cns-smart-contracts.md
smart-contracts/contract-reference/uns-smart-contracts.md
smart-contracts/overview/cns-architecture-overview.md
smart-contracts/overview/cns-uns-comparison.md
smart-contracts/overview/uns-architecture-overview.md
smart-contracts/quick-start/manage-domain-records.md
smart-contracts/quick-start/mint-subdomains.md
smart-contracts/quick-start/resolve-domains.md
smart-contracts/quick-start/reverse-resolve-domains.md
smart-contracts/quick-start/set-reverse-records.md
smart-contracts/sidebars.yaml

This PR introduces a new Information Architecture that subsequent categories will follow, and applies it to the Smart Contract category.
https://user-images.githubusercontent.com/13068878/222253967-4f9637d0-14b7-46f3-9d8f-c9c2a01df429.mov

Smart Contract IA

---

getting-started/test-domains/faucet.md
getting-started/test-domains/polygonscan.md
login-with-unstoppable/index.md
snippets/_supported-domain-endings.md

Add .kresus and .polygon to supported TLDs

docs: add .kresus and .polygon to supported TLDs

---

resolution/sidebars.yaml

Fixing typo in Resolution sidebars.yaml file

Resolution guides typo fix

---

developer-toolkit/advanced-use-cases/resolve-domains-browser/test-domains.md
developer-toolkit/advanced-use-cases/resolve-domains-in-web-applications.md
developer-toolkit/changelogs/resolution-changelog.md
developer-toolkit/changelogs/resolution-java-changelog.md
developer-toolkit/changelogs/resolution-swift-changelog.md
developer-toolkit/reference/ethereum-providers.md
developer-toolkit/resolution-integration-methods/resolution-libraries/resolution-go.md
developer-toolkit/resolution-integration-methods/resolution-libraries/resolution-java.md
developer-toolkit/resolution-integration-methods/resolution-libraries/resolution-swift.md
developer-toolkit/resolution-integration-methods/resolution-libraries/resolution.md
identity/quickstart/other-integration-paths/node-js.md
login-with-unstoppable/login-integration-guides/node-js-server-guide.md
resolution/guides/browser-resolution/test-domains.md
resolution/guides/ethereum-providers.md
resolution/quickstart/resolution.md
resolution/quickstart/reverse-resolution.md
resolution/sdks-and-libraries/go.md
resolution/sdks-and-libraries/java.md
resolution/sdks-and-libraries/javascript.md
resolution/sdks-and-libraries/swift.md
reverse-resolution/integration-guides/resolution-libraries.md
snippets/_namehashing-snippets.md

New resolution libs will be release with major version changes
[DT 1108](https://linear.app/unstoppable-domains/issue/DT-1108/update-related-docs-to-onboard-new-partners-to-use-api-key-in)

[DT 1108] Update public docs for resolution lib changes

---

domain-distribution-and-management/sidebars.yaml
resolution/sidebars.yaml
smart-contracts/sidebars.yaml

Add separator line to product side menu

feat: add separator line to product side menu

---

getting-started/test-domains/faucet.md
getting-started/test-domains/polygonscan.md
identity/overview/login-with-unstoppable.md
snippets/_supported-domain-endings.md

- add .anime and .manga to supported domains

feat: add .anime and .manga to supported domains

---

identity/quickstart/other-integration-paths/wagmi.md
identity/quickstart/retrieve-client-credentials.md
identity/sidebars.yaml

Add WAGMI integration path for LWU

feat: WAGMI integration path for LWU

---

openapi/partner.page.yaml

Enable Redocly CORS proxy for Partner API spec

---

resolution/guides/records-reference.md
resolution/sdks-and-libraries/javascript.md

With releasing of new ABI `getAddress`, update doc to reflect the format and API
[DT 1424](https://linear.app/unstoppable-domains/issue/DT-1424/update-docs-release)

Update docs for new address format

---

resolution/guides/records-reference.md

Fix to correct address format

---

openapi/loginref.page.yaml
openapi/partner.page.yaml
openapi/profile-v1.page.yaml
openapi/resolution.page.yaml

Simplify the API Reference docs sidebar

chore: simplify the API Reference docs sidebar

---

index.mdx

Fix unstoppable resolution link

fix: fix unstoppable resolution link

---

domain-distribution-and-management/overview.md
domain-distribution-and-management/partner-api-v2/guides/best-practices.md
domain-distribution-and-management/partner-api-v2/guides/check-domains-availability.md
domain-distribution-and-management/partner-api-v2/guides/claim-or-reserve-free-domains.md
domain-distribution-and-management/partner-api-v2/guides/faq.md
domain-distribution-and-management/partner-api-v2/guides/purchase-domains-with-redirect-url.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/deposit-or-withdraw.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/overview.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/return-domains.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/set-reverse-resolution.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/transfer.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/update-records.md
domain-distribution-and-management/partner-api-v2/quickstart/partner-api-v2-integration.md
domain-distribution-and-management/partner-api-v2/quickstart/purchase-domains-with-stripe.md
domain-distribution-and-management/partner-api-v2/quickstart/search-domains.md

Add partner api v2 cutoff warning

chore: add partner api v2 cutoff warning

---

domain-distribution-and-management/partner-api-v2/error-codes.md

chore: add partner api v2 cutoff warning to error codes page

---

domain-distribution-and-management/overview.md
domain-distribution-and-management/partner-api-v2/error-codes.md
domain-distribution-and-management/partner-api-v2/guides/best-practices.md
domain-distribution-and-management/partner-api-v2/guides/check-domains-availability.md
domain-distribution-and-management/partner-api-v2/guides/claim-or-reserve-free-domains.md
domain-distribution-and-management/partner-api-v2/guides/faq.md
domain-distribution-and-management/partner-api-v2/guides/purchase-domains-with-redirect-url.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/deposit-or-withdraw.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/overview.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/return-domains.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/set-reverse-resolution.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/transfer.md
domain-distribution-and-management/partner-api-v2/quickstart/manage-domains/update-records.md
domain-distribution-and-management/partner-api-v2/quickstart/partner-api-v2-integration.md
domain-distribution-and-management/partner-api-v2/quickstart/purchase-domains-with-stripe.md
domain-distribution-and-management/partner-api-v2/quickstart/search-domains.md

chore: update partner api v2 deprecation message wording

---

README.md
identity/sdk-and-libraries/web3-onboard.md

Fix minor typos

---

openapi/registry.page.yaml
openapi/sidebars.yaml
siteConfig.yaml

feat: add registry api openapi

---

domain-distribution-and-management/guides/on-chain-buy.md
domain-distribution-and-management/sidebars.yaml

Added a guide for using the registry API added in #149

Add On-chain Buy Guide

---

getting-started/sidebars.yaml
getting-started/test-domains/polygonscan.md

[REG-1246] docs: return 'get test domain on polygonscan page'

---

identity/overview/login-with-unstoppable.md
snippets/_supported-domain-endings.md

fix: supported tlds

---

getting-started/domain-registry-essentials/namehashing.md
openapi/metadata.page.yaml
openapi/sidebars.yaml
siteConfig.yaml

[no ticket] add standalone metadata spec to docs

---

domain-distribution-and-management/guides/sell-domains.md
sidebars.yaml
static/scripts/setup-pav3-guide.sh

Guide for how to create an Express.js backend to proxy the Partner API, and implement the proxy on a Next.js frontend

chore: PAv3 Implementation Guide

---

getting-started/overview.md

Updated note about emailing PE to get a developer domain to instead mention purchasing a $2 .unstoppable domain first before emailing PE per Matt

Fix: Test Domains Note

---

siteConfig.yaml

Changed copyright text 
From : Copyright © 2024 Unstoppable Domains Inc. All rights reserved. 
To: © Unstoppable Domains Inc. All Rights Reserved. 
Which aligns with the UD homepage

Fix: Update Copyright text
